apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: out-dns-svc-lb-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing-key
    metallb.universe.tf/address-pool: default
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 53
    targetPort: 53
  loadBalancerIP: 172.17.255.10
